### ISSUE TITLE
Unknown identifier errors

### ISSUE THREAD

**Issue by AJ-baj** [MenacingMecha/godot-psx-style-demo#11]
Running on Godot 4.0.2.stable

in lcd_post_process.gdshader:
line 33: Unknown identifier in expression: 'TEXTURE'.
in post_process_blur.gdshader:
line 52: Unknown identifier in expression: 'TEXTURE_PIXEL_SIZE'.
in pp_band-dither.gdshader:
line 9: Unknown identifier in expression: 'TEXTURE'.

and an invalid render mode error in psx_base.gdshaderinc:
line 1: Invalid render mode: 'LIT'.

**Comment by SeaKrill** [comment]
the invalid rendermode error doesnt effect the actual shader running. Adding:
```
#ifndef LIT
#define LIT unshaded
#endif
#ifndef CULL
#define CULL cull_disabled
#endif
#ifndef DEPTH
#define DEPTH depth_draw_opaque
#endif
```
ect...
infront of the render_mode in psx_base.gdsahderinc should clear it up if it bothers you.
more info here: https://docs.godotengine.org/en/stable/tutorials/shaders/shader_reference/shader_preprocessor.html

**Comment by MenacingMecha** [comment]
Reported this as a Godot issue at: https://github.com/godotengine/godot/issues/78482

Unless something changes, closing this for now

**Comment by MenacingMecha** [comment]
Fixed with https://github.com/MenacingMecha/godot-psx-style-demo/commit/ec07919eb79c126b6199230441081b2000310a21, per information from https://github.com/godotengine/godot/issues/78482#issuecomment-1599298120

**Comment by AJ-baj** [comment]
Hey! Thanks for looking into it, and sorry for the late reply. I've updated the shaders on my end now - can someone confirm that the precision_multiplier is still working as intended? I'm experiencing an issue where the vertex precision seems to be pretty low in the editor, but doesn't seem to be affected by the precision multiplier setting in psx_base.gdshaderinc, but in play mode the precision seems to be very high, and also doesn't seem to be affected by the setting

**Comment by MenacingMecha** [comment]
From a quick check, `precision_multiplier` seems to work fine for me.

If I'm understanding correctly, you're trying to adjust the global uniform in the project settings at run-time, correct?

This doesn't work, changing global uniforms at run-time must be done with a script. (https://docs.godotengine.org/en/stable/tutorials/shaders/shader_reference/shading_language.html#global-uniforms)

In future, please open a separate issue for separate issues.

**Comment by AJ-baj** [comment]
I'm not trying to change it during runtime, I would have said so if I was. I guess its an issue on my end though, if it works fine on your end.
