### ISSUE TITLE
Shaders don't work in Godot 4.1 Stable

### ISSUE THREAD

**Issue by mrjshzk** [MenacingMecha/godot-psx-style-demo#12]
Trying to use these in a godot 4.1 RC 3 project by copying the shader folder but can't get these to work
Thank you for your patience

**Comment by MenacingMecha** [comment]
Hi, could you provide details on what the error messages are?

IMO, it's too much (potentially wasted) effort to ensure support for non-stable versions, but it's possible whatever error you're having could persist into 4.1, so any info now could be of help down the line.

**Comment by mrjshzk** [comment]
Will test again in 4,1 stable in a bit and will let you know if the issues persist and if so, what are they

**Comment by mrjshzk** [comment]
Oh yeah, I'm so sorry. I didn't realize I had to do that... I really think you should add some install/usage instructions so this doesn't happen again

**Comment by MenacingMecha** [comment]
https://github.com/MenacingMecha/godot-psx-style-demo/commit/295d6e9d19aee5852459bacc64bea668a8b27248

**Comment by mrjshzk** [comment]
Perfect! :)
