### ISSUE TITLE
ShaderMaterials are broken in the latest version of Godot

### ISSUE THREAD

**Issue by Mimisor7** [MenacingMecha/godot-psx-style-demo#16]
![image](https://github.com/MenacingMecha/godot-psx-style-demo/assets/52045276/d70b5588-23a7-4530-89d7-591d28af0bb2)
I made a new Forward+ project in Godot v4.1.1.stable.official [bd6af8e0e] with just a camera and a MeshInstance3D that has a sphere mesh with a shadermaterial that uses the psx_lit shader just to see if this was just broken in more than one project. It's invisible once I run the project, and it's also throwing errors and warnings in the debugger and output. There's also no color parameters to be changed or image textures to be added in shader parameters like there used to be.
This project has all the files from the shaders folder in this repository. I don't think I am missing any files.

**Comment by Mimisor7** [comment]
Hold on... I didn't read the instructions... I thought it'd stay the same
How do I delete issues aaaa

**Comment by Mimisor7** [comment]
Hold on... I didn't read the instructions... I thought it'd stay the same
aaaa

**Comment by Mimisor7** [comment]
closed

**Comment by Mimisor7** [comment]
Actually, meshes still appear invisible for some reason, even if the shader parameters work again. I'm gonna open a seperate issue for that if I can't get meshes to display properly with these shaders within the next 48 hours

**Comment by Mimisor7** [comment]
actually I might've found the problem already... I'm gonna open a seperate issue for this
![image](https://github.com/MenacingMecha/godot-psx-style-demo/assets/52045276/12128233-26e4-4aea-b101-7b495beade5c)

**Comment by Mimisor7** [comment]
I found the solution to why this hasn't been working for me, and the answer was that upon comparing your project (that actually works) to mine, I found that I should've set the precision_multiplier's float value to 1. I had it on 0 for my project, because Godot automatically sets the value to 0 when you create a float. You should probably update the instructions to say that you should set the precision_multiplier's value to 1 upon creating the float in your project's shaderglobals so that this problem doesn't happen to anyone else again.

**Comment by MenacingMecha** [comment]
https://github.com/MenacingMecha/godot-psx-style-demo/commit/91bd24988f70636efca505e2c8022b143b61780e
