### ISSUE TITLE
Stuck at low FPS for no discernible reason.

### ISSUE THREAD

**Issue by natanmaia95** [MenacingMecha/godot-psx-style-demo#21]
I can't find the source for this limitation in the demo. Even though process time with my RTX 3050 is about 3ms (300FPS), the final render comes out at... 40ms a frame?
Even tried removing all shaders from the main scene but no clues.

images:
![image](https://github.com/MenacingMecha/godot-psx-style-demo/assets/74799857/e717b6b7-df23-4cca-b623-a4288100b758)
![image](https://github.com/MenacingMecha/godot-psx-style-demo/assets/74799857/dbfc2c1b-afff-49a4-ba93-c16191af8f3d)

**Comment by MenacingMecha** [comment]
FPS is limited to 24 FPS for aesthetic purposes in the project settings, but this can easily be disabled.
https://github.com/MenacingMecha/godot-psx-style-demo/blob/91bd24988f70636efca505e2c8022b143b61780e/project.godot#L19

If this doesn't fix the FPS issue you're having, I'll re-open.
